### ISSUE TITLE
Not ideal exports shape

### ISSUE THREAD

**Issue by Andarist** [etienne-dldc/democrat#1]
IMHO you shouldn't export an object as default export - I strongly believe this is an anti-pattern and should not be spread any further. It prevents certain build-time optimizations such as tree-shaking. I would like to encourage you to change it to separate named exports, which could still be used as namespace like this:
```js
import * as Democrat from 'democrat'
```

Don't take this as an attack - it's a common "mistake" I encounter in the wild and my intentions are only good 😉  The project itself looks really cool!

**Comment by etienne-dldc** [comment]
Fixed in [v2.0.0-alpha.1](https://github.com/etienne-dldc/democrat/releases/tag/v2.0.0-alpha.1)
